// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: grpc/wukuard.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint   string   `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	PublicKey  string   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	AllowedIPs []string `protobuf:"bytes,3,rep,name=allowedIPs,proto3" json:"allowedIPs,omitempty"`
	MacAddress string   `protobuf:"bytes,4,opt,name=macAddress,proto3" json:"macAddress,omitempty"`
	Hostname   string   `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *Peer) Reset() {
	*x = Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_wukuard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_wukuard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_grpc_wukuard_proto_rawDescGZIP(), []int{0}
}

func (x *Peer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Peer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Peer) GetAllowedIPs() []string {
	if x != nil {
		return x.AllowedIPs
	}
	return nil
}

func (x *Peer) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Peer) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type NetWork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerList []*Peer `protobuf:"bytes,1,rep,name=peerList,proto3" json:"peerList,omitempty"`
}

func (x *NetWork) Reset() {
	*x = NetWork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_wukuard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWork) ProtoMessage() {}

func (x *NetWork) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_wukuard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWork.ProtoReflect.Descriptor instead.
func (*NetWork) Descriptor() ([]byte, []int) {
	return file_grpc_wukuard_proto_rawDescGZIP(), []int{1}
}

func (x *NetWork) GetPeerList() []*Peer {
	if x != nil {
		return x.PeerList
	}
	return nil
}

var File_grpc_wukuard_proto protoreflect.FileDescriptor

var file_grpc_wukuard_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x75, 0x6b, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x9c, 0x01, 0x0a, 0x04, 0x50,
	0x65, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x50, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x50, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x07, 0x4e, 0x65, 0x74,
	0x57, 0x6f, 0x72, 0x6b, 0x12, 0x26, 0x0a, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65,
	0x65, 0x72, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x33, 0x0a, 0x07,
	0x53, 0x79, 0x6e, 0x63, 0x4e, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x12, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x65, 0x72,
	0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x22,
	0x00, 0x42, 0x52, 0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x6c, 0x6f, 0x68, 0x65, 0x61, 0x67, 0x6e, 0x2e, 0x77, 0x75, 0x6b, 0x75, 0x61, 0x72, 0x64, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x42, 0x0c, 0x57, 0x75, 0x6b, 0x75, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x6f, 0x68, 0x65, 0x61, 0x67, 0x6e, 0x2f, 0x77, 0x75, 0x6b, 0x75, 0x61, 0x72, 0x64,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_wukuard_proto_rawDescOnce sync.Once
	file_grpc_wukuard_proto_rawDescData = file_grpc_wukuard_proto_rawDesc
)

func file_grpc_wukuard_proto_rawDescGZIP() []byte {
	file_grpc_wukuard_proto_rawDescOnce.Do(func() {
		file_grpc_wukuard_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_wukuard_proto_rawDescData)
	})
	return file_grpc_wukuard_proto_rawDescData
}

var file_grpc_wukuard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_wukuard_proto_goTypes = []interface{}{
	(*Peer)(nil),    // 0: grpc.Peer
	(*NetWork)(nil), // 1: grpc.NetWork
}
var file_grpc_wukuard_proto_depIdxs = []int32{
	0, // 0: grpc.NetWork.peerList:type_name -> grpc.Peer
	0, // 1: grpc.SyncNet.HeartBeat:input_type -> grpc.Peer
	1, // 2: grpc.SyncNet.HeartBeat:output_type -> grpc.NetWork
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_wukuard_proto_init() }
func file_grpc_wukuard_proto_init() {
	if File_grpc_wukuard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_wukuard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_wukuard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetWork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_wukuard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_wukuard_proto_goTypes,
		DependencyIndexes: file_grpc_wukuard_proto_depIdxs,
		MessageInfos:      file_grpc_wukuard_proto_msgTypes,
	}.Build()
	File_grpc_wukuard_proto = out.File
	file_grpc_wukuard_proto_rawDesc = nil
	file_grpc_wukuard_proto_goTypes = nil
	file_grpc_wukuard_proto_depIdxs = nil
}
